// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import profilesdk "github.com/oscarzhao/oscarzhao.github.io/examples/testing/profilesdk"

// UserProfileAPI is an autogenerated mock type for the UserProfileAPI type
type UserProfileAPI struct {
	mock.Mock
}

// Get provides a mock function with given fields: name
func (_m *UserProfileAPI) Get(name string) (*profilesdk.Profile, error) {
	ret := _m.Called(name)

	var r0 *profilesdk.Profile
	if rf, ok := ret.Get(0).(func(string) *profilesdk.Profile); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profilesdk.Profile)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
